### ISSUE TITLE
device code capital letter issue

### ISSUE THREAD

**Issue by serephus** [opticyclic/android_device_nubia_nx529j#2]
nx529j/NX529J
I'm trying to install a rom, but it throw a error: this package is for device: NX529J, your device is nx529j(or vice verse, not so sure)
is this a TWRP problem?

**Comment by opticyclic** [comment]
Based on the limited amount of information you provided, I'm not sure if this is a ROM issue or a TWRP issue.
Is this only for one specific ROM?

I am currently using Mokee https://download.mokeedev.com/?device=nx529j without issue.

Which ROM are you getting this error with?

**Comment by serephus** [comment]
@opticyclic 
This should be a issue which only occurs in a specific version of TWRP (should be TWRP_3.2.1-5_nx529j.img), I downloaded this version from Internet, and this issue occurs for both CM13 and XenonHD.
I then downloaded a different TWRP, and it works fine. (Seems like this version flash the ROM unconditionally).
Thanks for your quick reply.
